### ISSUE TITLE
How to expose a python class with two functions to Java Script?

### ISSUE THREAD

**Issue by vimalpatnaik** [samuelhwilliams/Eel#146]
Hey Guys,
I've a small python class I'd like to be able to call from Java script. I've put **@eel.expose** above the class and the two functions I've in this class but when I call eel.Classname($(".username").val()) I get a traceback call like below. 

Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "D:\Project\src\eel\__init__.py", line 194, in _process_message
    'value': return_val    }))
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Classname is not JSON serializable
2019-05-26T20:06:02Z <Greenlet "Greenlet-0" at 0x263ac8c3268: _process_message({'call': 1.5123839460874966, 'name': 'Classname', 'args, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError

Process finished with exit code -1

Please advise how to expose the python class. I'm on EEL v0.9 and python 3.7. All help is greatly appreciated.

**Comment by ChrisKnott** [comment]
What does this method return?

**Comment by vimalpatnaik** [comment]
One method returns a json back to java script and the other returns a text message, if was any error.

**Comment by vimalpatnaik** [comment]
> What does this method return?
One method returns a json back to java script and the other returns a text message, if was any error.

**Comment by ChrisKnott** [comment]
It seems like Python doesn't know how to turn the object in JSON. You can try using the object's internal dict; instead of saying ```return my_obj```, say ```return my_obj.__dict__```

**Comment by vimalpatnaik** [comment]
> It seems like Python doesn't know how to turn the object in JSON. You can try using the object's internal dict; instead of saying `return my_obj`, say `return my_obj.__dict__`

Thank you for your quick response, I got the below

Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "D:\Project\src\eel\__init__.py", line 194, in _process_message
    'value': return_val    }))
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Someone\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Classname is not JSON serializable
2019-05-27T10:51:44Z <Greenlet "Greenlet-0" at 0x1539f276378: _process_message({'call': 1.0744899374581174, 'name': 'Classname', 'args, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError

**Comment by ChrisKnott** [comment]
It's difficult to diagnose without the actual class definition. Basically, Python doesn't know how to turn some part of the object into JSON. It might be easier to just construct your own dictionary and populate it with the bits of data you need.

**Comment by vimalpatnaik** [comment]
> It's difficult to diagnose without the actual class definition. Basically, Python doesn't know how to turn some part of the object into JSON. It might be easier to just construct your own dictionary and populate it with the bits of data you need.

Thank you for responding, I am wondering if you could check, what I did is correct in the first place.

1. Do I have to put **@eel.expose** before the class or just before the function def or both? -- I've put them everywhere before the class name, each method including the __init__()
2. Do I need this before the __init__() ?
3. From Java script side can I simply call the class like **eel.Class_name(parm1, parm2)** or is there a different syntax? -- I used eel.Class_name(parm1, parm2

Sorry about my ignorance & thank you for your assistance. I had one method and it worked very well but since then I've added another method and I've used python class to wrap two methods and I'm unable to get it to work from Java script and get a traceback call as above.

**Comment by samuelhwilliams** [comment]
Eel doesn't currently support exposing class methods, however #180 is an issue raised recently that proposes adding support. I'm going to close this off and track progress there.
