### ISSUE TITLE
500 Internal Server Error on app.py start

### ISSUE THREAD

**Issue by ProHackTech** [samuelhwilliams/Eel#179]
I created 'app.py' file in the main project directory. Then created 'web' folder with 'main.html' inside it. Initialized app.py as shown in the documentation.

On app.py start, chrome window opens with 500 error code. The following are the logs on console:

```
Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\_ffi\loop.py", line 234, in python_check_callback                                                                                                      PS C:\Users\da74\Documents\GitHub\FreshProxies\GUI> python app.py                                                       Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                           PS C:\Users\da74\Documents\GitHub\FreshProxies\GUI> python app.py --app                                                 Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\_ffi\loop.py", line 234, in python_check_callback                                                                                                      PS C:\Users\da74\Documents\GitHub\FreshProxies\GUI>                                                                     PS C:\Users\da74\Documents\GitHub\FreshProxies\GUI> python app.py --app                                                 Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\_ffi\loop.py", line 234, in python_check_callback                                                                                                          def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument                                      KeyboardInterrupt                                                                                                       2019-08-12T02:05:58Z                                                                                                    STARTED SERVER                                                                                                          Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)
  File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)
  File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static
    return btl.static_file(path, root=root_path)
NameError: name 'root_path' is not defined
Traceback (most recent call last):
  File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)
PS C:\Users\da74\Documents\GitHub\FreshProxies\GUI> python app.py --app                                                 Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 862, in _handle          return route.call(**args)                                                                                             File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bottle.py", line 1742, in wrapper         rv = callback(*a, **ka)                                                                                               File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 164, in _static                                                                                                                            return btl.static_file(path, root=root_path)                                                                        NameError: name 'root_path' is not defined                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\_ffi\loop.py", line 234, in python_check_callback                                                                                                          def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument                                      KeyboardInterrupt                                                                                                       2019-08-12T02:14:13Z                                                                                                    STARTED SERVER                                                                                                          Traceback (most recent call last):                                                                                        File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\_ffi\loop.py", line 234, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument
KeyboardInterrupt
2019-08-12T02:14:16Z
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    eel.sleep(10)
  File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eel\__init__.py", line 135, in sleep      gvt.sleep(seconds)
  File "C:\Users\da74\AppData\Local\Programs\Python\Python37-32\lib\site-packages\gevent\hub.py", line 159, in sleep        hub.wait(t)
  File "src\gevent\_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src\gevent\_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src\gevent\_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch    File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch    File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch    File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
KeyboardInterrupt
```

There is clearly an error with the script. I have Windows 10 x64 with everything else working. My chrome configurations are default out of the box. Windows is fresh installed. Tried everything possible, but there is no such issue found on internet so far with Eel since less people use this.

**Comment by ChrisKnott** [comment]
It looks like maybe you called `eel.start()` without calling `eel.init()`...?

**Comment by samuelhwilliams** [comment]
Based on @ChrisKnott's feedback above and the lack of response, I'm going to conclude that he was correct and your situation is now working.

If we're wrong, please comment on this issue and we'll take another look.
