### ISSUE TITLE
Error while passing middleware to eel

### ISSUE THREAD

**Issue by RahulBadenkal** [samuelhwilliams/Eel#228]
Hi, I was just trying to pass a beaker middleware to eel (related to #199 ) but got the following error:

> Traceback (most recent call last):
  File "/<path>/run.py", line 52, in start_app
    eel.start(start_html_page, mode='chrome', port=0, app=app)
  File "/<path>/venv/lib/python3.6/site-packages/eel/__init__.py", line 161, in start
    run_lambda()
  File "/<path>/venv/lib/python3.6/site-packages/eel/__init__.py", line 151, in run_lambda
    app.route(path=route_path, callback=route_func, **route_kwargs)
AttributeError: 'SessionMiddleware' object has no attribute 'route'

Code is same as in the linked issue

**Comment by samuelhwilliams** [comment]
This should be fixed in the latest v0.12.2 release @RahulBadenkal
