### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by webeasyplay** [samuelhwilliams/Eel#347]
**Is your feature request related to a problem? Please describe.**
When I use Pycharm debug mode.
There are few errors that are generated in the console.

========================================================
Original exception was:
SystemError: ..\Objects\codeobject.c:851: bad argument to internal function
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "_pydevd_frame_eval\pydevd_frame_evaluator_win32_36_32.pyx", line 196, in _pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_func_code_info
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.FuncCodeInfo'> returned a result with an error set
Exception ignored in: '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_bytecode_while_frame_eval'
Traceback (most recent call last):
  File "_pydevd_frame_eval\pydevd_frame_evaluator_win32_36_32.pyx", line 196, in _pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_func_code_info
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.FuncCodeInfo'> returned a result with an error set
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_breakpoints.py", line 169, in _fallback_excepthook
SystemError: error return without exception set
Original exception was:
SystemError: ..\Objects\codeobject.c:851: bad argument to internal function
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "_pydevd_frame_eval\pydevd_frame_evaluator_win32_36_32.pyx", line 196, in _pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_func_code_info
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.FuncCodeInfo'> returned a result with an error set
Exception ignored in: '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_bytecode_while_frame_eval'
Traceback (most recent call last):
  File "_pydevd_frame_eval\pydevd_frame_evaluator_win32_36_32.pyx", line 196, in _pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.get_func_code_info
SystemError: <class '_pydevd_frame_eval.pydevd_frame_evaluator_win32_36_32.FuncCodeInfo'> returned a result with an error set
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_breakpoints.py", line 169, in _fallback_excepthook
SystemError: error return without exception set
===============================================

**Describe the solution you'd like**
I was found the solution.
![image](https://user-images.githubusercontent.com/12272185/86536841-65bc0880-bf1d-11ea-8777-8ca113f4d730.png)
![image](https://user-images.githubusercontent.com/12272185/86536855-85533100-bf1d-11ea-9537-45c6d6f92083.png)
Add two environment variable
**_PYDEVD_USE_CYTHON=No
PYDEVD_USE_FRAME_EVAL=No_**

It's works perfect after changes.

**Describe alternatives you've considered**

**Additional context**
Can you add this article to the wiki?
I spent a lot of time to fix this problem.
Thank you.

**Comment by samuelhwilliams** [comment]
Hmm, interesting. I actually don't get these errors myself when I'm running a trivial program (example 3), so it feels like we'd have to dig down a bit more to understand this. Can you provide more info about your platform please? OS, PyCharm version, python version, installed packages, etc.

Thanks!
