### ISSUE TITLE
Pyinstaller traceback error eel 

### ISSUE THREAD

**Issue by nj-AllAboutCode** [samuelhwilliams/Eel#68]
<h4>
<br>
<br>
<p>
 I tried to build (package) eel program using pyinstaller.<br>
Pyinstaller workes fine and build the app successfully.<br>
But when i tried to run the exe in dist folder i got following error:- <br><br>
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PythonEel\oslister.py", line 1, in <module>
    import eel, os, random
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eel\__init__.py", line 2, in <module>
    import gevent as gvt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gevent\__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gevent\_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'
[1240] Failed to execute script oslister` 
</p>
<h5>Help Needed</h5></h4>

**Comment by sdc-hyoshino** [comment]
I also experienced the same problem.
I do not know whether it is correct, but I generated an exe file in the following way.

1. Copy pyinstaller execution command
2. Add the following to the copied command　＆ run
` --add-data C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gevent";"gevent"`

**Comment by samuelhwilliams** [comment]
Hi. I'm closing this issue due to inactivity and the belief that it has been fixed in a more recent release of Eel.

If you continue to have this problem, please leave a message here or open a new issue.

Thanks.
